export const loginActions = {
    LOGIN_BEGIN: 'LOGIN_BEGIN', 
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE'
}

export const sitesActions = {
    FETCH_BEGIN: 'FETCH_SITES_BEGIN',
    FETCH_SUCCESS: 'FETCH_SITES_SUCCESS',
    FETCH_FAILURE: 'FETCH_SITES_FAILURE'
}

export const bookingsActions = {
    FETCH_BEGIN: 'FETCH_BOOKINGS_BEGIN',
    FETCH_SUCCESS: 'FETCH_BOOKINGS_SUCCESS',
    FETCH_FAILURE: 'FETCH_BOOKINGS_FAILURE'
}